spring:
  application:
    name: mindblowr
  profiles:
    active: default
version: @project.version@
description: @project.description@
java:
  version: @java.version@
api:
  basePath: '/'
oauth2:
  resourceIds: mindblowr
  scopes: GUEST
  grantTypes: client_credentials, password, refresh_token
  authorities: GUEST
  clientId: myclient
  clientSecret: test
  host: oauth2-server
  port: 8081
server:
  port: 8080
logging:
  level:
    io.laegler.mindblowr: TRACE
    org.springframework.data: DEBUG
    org.hibernate.SQL: DEBUG