spring:
  application:
    name: mindblowr
  profiles:
    active: default
version: 0.0.1-SNAPSHOT
description: mindblowr - learning things in a new way
java:
  version: 1.8.0_171
api:
  basePath: '/'
oauth2:
  resourceIds: mindblowr
  scopes: GUEST
  grantTypes: client_credentials, password, refresh_token
  authorities: GUEST
  clientId: myclient
  clientSecret: test
  host: oauth2-server
  port: 8081
server:
  port: 8080
logging:
  level:
    io.laegler.mindblowr: TRACE
    org.springframework.data: DEBUG
    org.hibernate.SQL: DEBUG